#!/usr/bin/env python3
"""Turn a Studio RFdiffusion3 request into a campaign the RFD3 scripts can run.

Studio does not orchestrate RFdiffusion3 itself. The production pipeline lives
in the RFD3 repo and is already validated end to end; this script only prepares
its inputs:

    <campaign>/config/design.yaml      DesignInputSpecification + conditioning
    <campaign>/config/ligand.smi       SMILES (small-molecule campaigns)
    <campaign>/config/campaign.json    the config run_rfd3_nise_campaign.py reads
    <campaign>/assets/ligand/…         generated CCD component + PDB, for SMILES

after which the campaign is launched with the RFD3 repo's own
``launch_rfd3_nise_campaign.py``.

Two details are load-bearing and easy to get wrong:

1. **Do not write `length` into the YAML.** Foundry's ``length`` is the *total*
   component count, not the binder length, so a 65-aa binder against a contig
   carrying a fixed motif needs a larger total. ``design_from_yaml.py`` already
   computes that from the contig; writing our own ``length`` here reintroduces
   exactly the ``No valid selections possible with the given constraints``
   failure that this pipeline was fixed for.

2. **Do not add the ligand twice.** When the ligand is supplied through
   ``input:`` plus ``ligand:``, naming it again in the contig duplicates every
   ligand atom in the Foundry/MLX output. Small-molecule campaigns therefore
   carry no contig at all.

Reads the Studio request as JSON on argv[1]; prints ``PREPOK|<campaign.json>``
on success, or ``PREPFAIL|<reason>`` and exit 1.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


def fail(message: str) -> None:
    print(f"PREPFAIL|{message}")
    sys.exit(1)


def yaml_quote(value: str) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def ligand_chain_resnum(pdb_path: Path, resname: str | None) -> str | None:
    """Find the chain+resnum key for the ligand, e.g. 'L1' or 'C1'.

    Selection keys in the design YAML address the ligand this way. Guessing
    wrong means the preflight in design_from_yaml.py rejects the spec, which is
    the intended failure mode -- loudly, in a second, rather than minutes into
    Foundry.
    """
    try:
        for line in pdb_path.read_text(errors="replace").splitlines():
            if not line.startswith("HETATM"):
                continue
            name = line[17:20].strip()
            if resname and name != resname.strip().upper():
                continue
            chain = line[21].strip() or "A"
            return f"{chain}{int(line[22:26])}"
    except (OSError, ValueError):
        return None
    return None


def write_design_yaml(req: dict, campaign: Path, ligand_input: Path | None,
                      selection_key: str | None) -> Path:
    lines = ["# Generated by NanoHunter Studio. Safe to edit and re-run by hand:",
             "#   .venv/bin/python scripts/design_from_yaml.py <this file> --lengths ...",
             ""]
    name = req["design_name"]
    lines.append(f"{name}:")

    def emit(key: str, value: str) -> None:
        lines.append(f"  {key}: {value}")

    def emit_selection(key: str, atoms: list[str]) -> None:
        if not atoms or not selection_key:
            return
        lines.append(f"  {key}:")
        lines.append(f"    {yaml_quote(selection_key)}: {yaml_quote(','.join(atoms))}")

    if req["target_kind"] == "small_molecule":
        if ligand_input is None:
            fail("No ligand structure was produced.")
        emit("input", yaml_quote(str(ligand_input)))
        emit("ligand", yaml_quote(req["component_id"]))
        # No contig: input + ligand already introduce the component. Naming it
        # again duplicates every ligand atom.
    else:
        emit("input", yaml_quote(req["target_structure"]))
        # Contig carries the binder range plus the fixed target motif;
        # design_from_yaml.py converts binder length -> total component length.
        emit("contig", yaml_quote(req["contig"]))

    emit("redesign_motif_sidechains", "false")
    if req.get("is_non_loopy") is not None:
        emit("is_non_loopy", "true" if req["is_non_loopy"] else "false")
    if req.get("infer_ori_strategy"):
        emit("infer_ori_strategy", str(req["infer_ori_strategy"]))
    if req.get("ori_token"):
        emit("ori_token", "[" + ", ".join(f"{v:.3f}" for v in req["ori_token"]) + "]")

    if req["target_kind"] == "small_molecule":
        lines.append("  select_fixed_atoms:")
        # "ALL", not an empty string: the pinned Foundry build treats "" as an
        # empty selection rather than as everything.
        lines.append(f"    {yaml_quote(req['component_id'])}: {yaml_quote('ALL')}")

    conditions = req.get("conditions", {})
    for spec_key, condition in (("select_buried", "buried"),
                                ("select_exposed", "exposed"),
                                ("select_hbond_donor", "hbondDonor"),
                                ("select_hbond_acceptor", "hbondAcceptor"),
                                ("select_hotspots", "hotspot")):
        atoms = sorted(site for site, applied in conditions.items() if condition in applied)
        if condition == "hotspot" and req["target_kind"] == "protein":
            # Protein hotspots are residues addressed directly, not atoms under
            # a ligand key.
            if atoms:
                lines.append("  select_hotspots:")
                for residue in atoms:
                    lines.append(f"    {yaml_quote(residue)}: {yaml_quote('ALL')}")
            continue
        emit_selection(spec_key, atoms)

    path = campaign / "config" / "design.yaml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    return path


def prepare_ligand(req: dict, campaign: Path, rfd3_root: Path) -> tuple[Path, Path]:
    """SMILES -> explicit CCD component + chain-L PDB, via the RFD3 script."""
    spec = {"smiles": req["smiles"]}
    for key, condition in (("exposed", "exposed"), ("buried", "buried"),
                           ("hbond_donor", "hbondDonor"), ("hbond_acceptor", "hbondAcceptor"),
                           ("hotspots", "hotspot")):
        atoms = sorted(site for site, applied in req.get("conditions", {}).items()
                       if condition in applied)
        if atoms:
            spec[key] = {"LIGAND": ",".join(atoms)}

    spec_path = campaign / "config" / "ligand_spec.json"
    spec_path.parent.mkdir(parents=True, exist_ok=True)
    spec_path.write_text(json.dumps(spec, indent=2) + "\n")

    out_dir = campaign / "assets" / "ligand"
    log = campaign / "logs" / "prepare_ligand.log"
    log.parent.mkdir(parents=True, exist_ok=True)
    cmd = [sys.executable, str(rfd3_root / "scripts" / "prepare_ligand_target.py"),
           "--spec", str(spec_path),
           "--component-id", req["component_id"],
           "--output-dir", str(out_dir),
           "--design-name", req["design_name"],
           "--base-json", str(campaign / "config" / "ligand_base_input.json")]
    with log.open("w") as handle:
        result = subprocess.run(cmd, cwd=rfd3_root, stdout=handle, stderr=subprocess.STDOUT,
                                env={**_env(), "DEBUG": "false"})
    if result.returncode:
        tail = "\n".join(log.read_text(errors="replace").splitlines()[-8:])
        fail(f"Could not build the ligand component.\n{tail}")

    pdb = out_dir / f"{req['component_id'].upper()}.pdb"
    ccd = out_dir / "ccd"
    if not pdb.exists():
        fail(f"Expected a ligand PDB at {pdb}.")
    return pdb, ccd


def _env() -> dict:
    import os
    return dict(os.environ)


def main() -> None:
    if len(sys.argv) < 2:
        fail("No request file given.")
    try:
        req = json.loads(Path(sys.argv[1]).read_text())
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"Could not read the request: {exc}")

    rfd3_root = Path(req["rfd3_root"]).resolve()
    if not (rfd3_root / "scripts" / "design_from_yaml.py").exists():
        fail(f"{rfd3_root} does not contain design_from_yaml.py — update your RFdiffusion3 checkout.")
    campaign = Path(req["campaign_dir"]).resolve()
    campaign.mkdir(parents=True, exist_ok=True)
    (campaign / "config").mkdir(exist_ok=True)

    ligand_input: Path | None = None
    ccd_mirror: Path | None = None
    selection_key: str | None = None

    if req["target_kind"] == "small_molecule":
        if req.get("ligand_source") == "structure_file":
            ligand_input = Path(req["ligand_structure"]).resolve()
            if not ligand_input.exists():
                fail(f"No such file: {ligand_input}")
            selection_key = ligand_chain_resnum(ligand_input, req.get("ligand_residue"))
            if selection_key is None:
                fail("Could not find that ligand residue in the structure file.")
        else:
            ligand_input, ccd_mirror = prepare_ligand(req, campaign, rfd3_root)
            selection_key = ligand_chain_resnum(ligand_input, req["component_id"]) or "L1"
        smi = campaign / "config" / "ligand.smi"
        if not req.get("smiles"):
            fail("A SMILES string is required: LASErMPNN and the Boltz affinity head both need it.")
        smi.write_text(req["smiles"].strip() + "\n")
    else:
        selection_key = None

    design_yaml = write_design_yaml(req, campaign, ligand_input, selection_key)

    config = {
        "campaign_dir": str(campaign),
        "design_name": req["design_name"],
        "design_yaml": str(design_yaml),
        "component_id": req.get("component_id"),
        "lengths": req["lengths"],
        "num_backbones": req["num_backbones"],
        "rfd3_timesteps": req["timesteps"],
        "rfd3_recycles": req["recycles"],
        "rfd3_batch_size": req["batch_size"],
        "rfd3_queues_per_bin": req["queues_per_bin"],
        "rfd3_precision": req["precision"],
        "seed_base": req["seed_base"],
        "sequences_per_backbone": req["sequences_per_backbone"],
        "mpnn_max_parallel": req.get("mpnn_max_parallel", 6),
        "boltz_chunk_size": req.get("boltz_chunk_size", 50),
        "boltz_calibrate_n": req.get("boltz_calibrate_n", 12),
        "top_n": req["top_n"],
    }
    if req["target_kind"] == "small_molecule":
        config["smiles_file"] = str(campaign / "config" / "ligand.smi")
        if ccd_mirror is not None:
            config["ccd_mirror"] = str(ccd_mirror)
        elif req.get("ccd_mirror"):
            config["ccd_mirror"] = req["ccd_mirror"]
    else:
        config["target_kind"] = "protein"

    config_path = campaign / "config" / "campaign.json"
    config_path.write_text(json.dumps(config, indent=2) + "\n")

    # Cheap, GPU-free validation: design_from_yaml's preflight resolves every
    # selection key and atom name against the input structure. A mistyped atom
    # fails here in a second instead of minutes into Foundry.
    check = subprocess.run(
        [sys.executable, str(rfd3_root / "scripts" / "design_from_yaml.py"), str(design_yaml),
         "--name", req["design_name"], "--output", str(campaign),
         "--lengths", ",".join(map(str, req["lengths"])), "--stage", "check"],
        cwd=rfd3_root, capture_output=True, text=True,
        env={**_env(), "DEBUG": "false", "TOKENIZERS_PARALLELISM": "false",
             **({"CCD_MIRROR_PATH": str(ccd_mirror)} if ccd_mirror else {})},
    )
    if check.returncode:
        message = (check.stderr or check.stdout or "").strip().splitlines()
        fail("Your design settings were rejected:\n" + "\n".join(message[-8:]))

    print(f"PREPOK|{config_path}")


if __name__ == "__main__":
    main()
