#!/usr/bin/env python3
"""Generate backbones across all length bins and flatten into one numbered set.

Each bin gets its own fixture (one binder length), so backbones for a bin are
generated by running ``generate_backbones.py`` --queues-per-bin (default 2)
times concurrently, each doing native batch --batch-size (default 8) -- the
measured M4 Max throughput optimum for a mixed-length queue (two shape
queues x native batch 8 = 9.6 designs/min, README "Apple-Silicon
performance"). Bins run one at a time (not all bins concurrently) to avoid
oversubscribing MPS. Every downstream script expects a flat
``rfd3/backbones/design_%04d.pdb`` set, so after each bin's queues finish,
this script symlinks its PDBs into that flat, globally numbered directory
and records which bin/length each design came from.
"""

from __future__ import annotations

import argparse
from collections import Counter
import csv
import json
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run_queue(bin_spec: dict, out_dir: Path, num_designs: int, args, seed_start: int) -> subprocess.Popen:
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable, str(ROOT / "scripts" / "generate_backbones.py"),
        "--fixture", bin_spec["fixture"], "--output", str(out_dir),
        "--num-designs", str(num_designs), "--steps", str(args.steps),
        "--recycle", str(args.recycle), "--batch-size", str(args.batch_size),
        "--precision", args.precision, "--seed-start", str(seed_start),
    ]
    if args.ligand_code:
        cmd += ["--ligand-code", args.ligand_code]
    if bin_spec.get("motif_source_residues"):
        cmd += ["--motif-residues", ",".join(bin_spec["motif_source_residues"])]
        cmd += ["--motif-atoms-json", json.dumps(bin_spec.get("motif_fixed_atoms") or {})]
    log = (out_dir / "queue.log").open("w")
    return subprocess.Popen(cmd, cwd=ROOT, stdout=log, stderr=subprocess.STDOUT), log


def split_quota(quota: int, n: int) -> list[int]:
    base, remainder = divmod(quota, n)
    return [base + (1 if i < remainder else 0) for i in range(n)]


def bin_directory_name(bin_spec: dict, repeated_lengths: set[int]) -> str:
    length = int(bin_spec["length"])
    return (f"bin{int(bin_spec['bin_index']):03d}_L{length}"
            if length in repeated_lengths else f"L{length}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bin-manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True, help="rfd3/ dir inside the campaign")
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--queues-per-bin", type=int, default=2)
    parser.add_argument("--precision", choices=["fp32", "bf16", "int8"], default="bf16")
    parser.add_argument("--steps", type=int, default=200)
    parser.add_argument("--recycle", type=int, default=2)
    parser.add_argument("--ligand-code", default=None)
    args = parser.parse_args()

    manifest = json.loads(args.bin_manifest.read_text())
    if args.ligand_code is None:
        args.ligand_code = manifest.get("component_id")

    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    flat_dir = output / "backbones"
    flat_dir.mkdir(exist_ok=True)

    bin_records = []
    repeated_lengths = {
        length for length, count in Counter(b["length"] for b in manifest["bins"]).items()
        if count > 1
    }
    for b in manifest["bins"]:
        length, quota, name = b["length"], b["quota"], b["name"]
        # Several ligand conformers commonly share a binder length. They must
        # not share a done marker, queues, or generated PDBs.
        bin_dir = output / bin_directory_name(b, repeated_lengths)
        queue_dirs = [bin_dir / f"queue{q}" for q in range(args.queues_per_bin)]
        done_marker = bin_dir / "bin_done.json"
        if done_marker.exists():
            print(f"L{length}: cached ({quota} designs)")
            cached = json.loads(done_marker.read_text())
            if b.get("origin"):
                cached["origin"] = b["origin"]
            bin_records.append(cached)
            continue

        quotas = split_quota(quota, args.queues_per_bin)
        seed_offset = b["seed"] * 1_000_000
        started = time.time()
        procs = []
        for q, (qdir, qn) in enumerate(zip(queue_dirs, quotas, strict=True)):
            if qn == 0:
                continue
            proc, log = run_queue(b, qdir, qn, args, seed_offset + q * 500_000)
            procs.append((proc, log, qdir))
        failures = []
        for proc, log, qdir in procs:
            rc = proc.wait()
            log.close()
            if rc != 0:
                failures.append(str(qdir))
        if failures:
            raise SystemExit(f"generate_backbones.py failed for: {failures}")
        wall = time.time() - started

        pdbs = sorted(
            p for qdir in queue_dirs for p in (qdir / "backbones").glob("design_*.pdb")
        )
        if len(pdbs) != quota:
            raise SystemExit(
                f"L{length}: expected exactly {quota} backbone PDBs, found {len(pdbs)}; "
                "refusing to mark an under/over-filled bin complete"
            )
        record = {
            "bin_index": b["bin_index"], "length": length, "quota": quota,
            "wall_sec": wall, "sec_per_design": wall / quota if quota else 0.0,
            "pdbs": [str(p) for p in pdbs],
            "origin": b.get("origin"),
        }
        done_marker.write_text(json.dumps(record, indent=2) + "\n")
        bin_records.append(record)
        print(f"L{length}: {len(pdbs)} designs in {wall:.1f}s ({wall / max(quota,1):.2f}s/design)")

    # Flatten into a single globally numbered, flat backbone set.
    rows = []
    index = 0
    for record in bin_records:
        for pdb in record["pdbs"]:
            index += 1
            name = f"design_{index:04d}"
            link = flat_dir / f"{name}.pdb"
            if link.exists() or link.is_symlink():
                link.unlink()
            link.symlink_to(Path(pdb).resolve())
            origin = record.get("origin") or {}
            rows.append({
                "design": name, "design_index": index, "bin_length": record["length"],
                "backbone_pdb": str(link), "source_pdb": pdb,
                "origin_label": origin.get("label"),
                "origin_xyz": origin.get("xyz"),
                "origin_anchor_residues": origin.get("anchor_residues"),
                "origin_placement_mode": origin.get("placement_mode"),
            })

    with (output / "backbone_metrics.csv").open("w", newline="") as handle:
        # Merge in the per-design RFD3 metrics from each queue's own results/.
        merged_rows = []
        for row in rows:
            src = Path(row["source_pdb"])
            result_path = src.parent.parent / "results" / (src.stem + ".json")
            metrics = json.loads(result_path.read_text()) if result_path.exists() else {}
            merged_rows.append({**metrics, **row})
        fields = sorted({key for row in merged_rows for key in row})
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows([
            {key: json.dumps(value, sort_keys=True) if isinstance(value, (dict, list)) else value
             for key, value in row.items()}
            for row in merged_rows
        ])
    fixed_map = {row["backbone_pdb"]: row.get("fixed_residues", "")
                 for row in merged_rows if row.get("fixed_residues")}
    if fixed_map:
        (output / "fixed_residues_multi.json").write_text(
            json.dumps(fixed_map, indent=2, sort_keys=True) + "\n")

    (output / "run_manifest.json").write_text(
        json.dumps({"num_designs": len(rows), "bins": bin_records}, indent=2) + "\n"
    )
    print(f"flattened {len(rows)} backbones -> {flat_dir}")


if __name__ == "__main__":
    main()
